{
 "title": "Portfolio App — nginx metrics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total successful requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(portfolio_requests_total{namespace=\"portfolio\", status=~\"2..\"})\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request rate by HTTP status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (status) (rate(portfolio_requests_total{namespace=\"portfolio\"}[2m]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "nginx connection states",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "nginx_connections_accepted{namespace=\"portfolio\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "nginx_connections_active{namespace=\"portfolio\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "nginx_connections_handled{namespace=\"portfolio\"}\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "nginx_connections_waiting{namespace=\"portfolio\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods Ready",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_status_ready{namespace=\"portfolio\", condition=\"true\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod restarts",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pod) (kube_pod_container_status_restarts_total{namespace=\"portfolio\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active connections",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_connections_active{namespace=\"portfolio\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request rate (req/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total{namespace=\"portfolio\"}[2m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}