apiVersion: v1
kind: Service
metadata:
  name: {{ include "portfolio.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "portfolio.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "portfolio.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http

    {{- if .Values.nginxExporter.enabled }}
    - name: metrics
      port: 9113
      targetPort: nginx-metrics
    {{- end }}

    {{- if .Values.metricsExporter.enabled }}
    - name: app-metrics
      port: 8000
      targetPort: app-metrics
    {{- end }}