{{- if or .Values.nginxExporter.enabled .Values.metricsExporter.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "portfolio.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "portfolio.labels" . | nindent 4 }}
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      {{- include "portfolio.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    {{- if .Values.nginxExporter.enabled }}
    - port: metrics
      path: /metrics
      interval: 30s
    {{- end }}
    {{- if .Values.metricsExporter.enabled }}
    - port: app-metrics
      path: /metrics
      interval: 15s
    {{- end }}
{{- end }}